BEGIN;

DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS otp_codes;
DROP TABLE IF EXISTS ingredients;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS bills;
DROP TABLE IF EXISTS inventory_items;
DROP TABLE IF EXISTS vendors;
DROP TABLE IF EXISTS menu_items;
DROP TABLE IF EXISTS dining_tables;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS user_role;

COMMIT;