// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: analytics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAvgItemsPerOrder = `-- name: GetAvgItemsPerOrder :one
SELECT ROUND(COALESCE(AVG(quantity), 0)::NUMERIC, 2)::FLOAT FROM orders
`

func (q *Queries) GetAvgItemsPerOrder(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, getAvgItemsPerOrder)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const getCategoryDistribution = `-- name: GetCategoryDistribution :many
SELECT COALESCE(category, 'Others')::TEXT as name, (COUNT(*) * 100.0 / NULLIF((SELECT COUNT(*) FROM orders), 0))::INT as percentage
FROM menu_items m JOIN orders o ON o.menu_item_id = m.id
GROUP BY category
`

type GetCategoryDistributionRow struct {
	Name       string `json:"name"`
	Percentage int32  `json:"percentage"`
}

func (q *Queries) GetCategoryDistribution(ctx context.Context) ([]GetCategoryDistributionRow, error) {
	rows, err := q.db.Query(ctx, getCategoryDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryDistributionRow
	for rows.Next() {
		var i GetCategoryDistributionRow
		if err := rows.Scan(&i.Name, &i.Percentage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInventoryStats = `-- name: GetInventoryStats :one
SELECT 
    COUNT(*)::BIGINT as total_items,
    COUNT(*) FILTER (WHERE quantity <= min_stock / 2)::BIGINT as critical_items,
    COUNT(*) FILTER (WHERE quantity <= min_stock AND quantity > min_stock / 2)::BIGINT as low_stock_items
FROM inventory_items
`

type GetInventoryStatsRow struct {
	TotalItems    int64 `json:"total_items"`
	CriticalItems int64 `json:"critical_items"`
	LowStockItems int64 `json:"low_stock_items"`
}

func (q *Queries) GetInventoryStats(ctx context.Context) (GetInventoryStatsRow, error) {
	row := q.db.QueryRow(ctx, getInventoryStats)
	var i GetInventoryStatsRow
	err := row.Scan(&i.TotalItems, &i.CriticalItems, &i.LowStockItems)
	return i, err
}

const getLowStockItems = `-- name: GetLowStockItems :many
SELECT name, ROUND(quantity::NUMERIC, 2)::FLOAT as current, unit, ROUND(min_stock::NUMERIC, 2)::FLOAT as threshold, 
    CASE WHEN quantity <= min_stock / 2 THEN 'critical' ELSE 'low' END as severity
FROM inventory_items 
WHERE quantity <= min_stock
ORDER BY quantity ASC LIMIT 10
`

type GetLowStockItemsRow struct {
	Name      string  `json:"name"`
	Current   float64 `json:"current"`
	Unit      string  `json:"unit"`
	Threshold float64 `json:"threshold"`
	Severity  string  `json:"severity"`
}

func (q *Queries) GetLowStockItems(ctx context.Context) ([]GetLowStockItemsRow, error) {
	rows, err := q.db.Query(ctx, getLowStockItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLowStockItemsRow
	for rows.Next() {
		var i GetLowStockItemsRow
		if err := rows.Scan(
			&i.Name,
			&i.Current,
			&i.Unit,
			&i.Threshold,
			&i.Severity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPeakHour = `-- name: GetPeakHour :one
SELECT COALESCE(TO_CHAR(ordered_at, 'HH24:00'), '19:00')::TEXT
FROM orders GROUP BY 1 ORDER BY COUNT(*) DESC LIMIT 1
`

func (q *Queries) GetPeakHour(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getPeakHour)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const getTodayOrderCount = `-- name: GetTodayOrderCount :one
SELECT COUNT(*)::BIGINT as count
FROM orders
WHERE ordered_at >= CURRENT_DATE
`

func (q *Queries) GetTodayOrderCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTodayOrderCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTodayRevenue = `-- name: GetTodayRevenue :one
SELECT COALESCE(SUM(m.price * o.quantity), 0)::FLOAT as revenue
FROM orders o
JOIN menu_items m ON o.menu_item_id = m.id
WHERE o.ordered_at >= CURRENT_DATE
`

func (q *Queries) GetTodayRevenue(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, getTodayRevenue)
	var revenue float64
	err := row.Scan(&revenue)
	return revenue, err
}

const getTopCategory = `-- name: GetTopCategory :one
SELECT COALESCE(category, 'Mains')::TEXT
FROM menu_items m JOIN orders o ON o.menu_item_id = m.id 
GROUP BY category ORDER BY COUNT(*) DESC LIMIT 1
`

func (q *Queries) GetTopCategory(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getTopCategory)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const getTopItems = `-- name: GetTopItems :many
SELECT 
    m.name, 
    SUM(o.quantity)::BIGINT as units_sold, 
    SUM(m.price * o.quantity)::FLOAT as revenue
FROM orders o
JOIN menu_items m ON o.menu_item_id = m.id
WHERE o.ordered_at >= CURRENT_DATE - INTERVAL '30 days'
GROUP BY m.name
ORDER BY units_sold DESC
LIMIT 5
`

type GetTopItemsRow struct {
	Name      string  `json:"name"`
	UnitsSold int64   `json:"units_sold"`
	Revenue   float64 `json:"revenue"`
}

func (q *Queries) GetTopItems(ctx context.Context) ([]GetTopItemsRow, error) {
	rows, err := q.db.Query(ctx, getTopItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopItemsRow
	for rows.Next() {
		var i GetTopItemsRow
		if err := rows.Scan(&i.Name, &i.UnitsSold, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalSales30Days = `-- name: GetTotalSales30Days :one
SELECT COUNT(*)::BIGINT FROM orders WHERE ordered_at >= CURRENT_DATE - INTERVAL '30 days'
`

func (q *Queries) GetTotalSales30Days(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalSales30Days)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getWeeklyRevenue = `-- name: GetWeeklyRevenue :many
WITH days AS (
    SELECT generate_series(CURRENT_DATE - INTERVAL '6 days', CURRENT_DATE, '1 day')::date AS d
)
SELECT 
    TO_CHAR(d, 'Dy') as day_name,
    COALESCE(SUM(m.price * o.quantity), 0)::FLOAT as revenue,
    d as day_date
FROM days d
LEFT JOIN orders o ON o.ordered_at::date = d
LEFT JOIN menu_items m ON o.menu_item_id = m.id
GROUP BY d
ORDER BY d
`

type GetWeeklyRevenueRow struct {
	DayName string      `json:"day_name"`
	Revenue float64     `json:"revenue"`
	DayDate pgtype.Date `json:"day_date"`
}

func (q *Queries) GetWeeklyRevenue(ctx context.Context) ([]GetWeeklyRevenueRow, error) {
	rows, err := q.db.Query(ctx, getWeeklyRevenue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWeeklyRevenueRow
	for rows.Next() {
		var i GetWeeklyRevenueRow
		if err := rows.Scan(&i.DayName, &i.Revenue, &i.DayDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYesterdayOrderCount = `-- name: GetYesterdayOrderCount :one
SELECT COUNT(*)::BIGINT as count
FROM orders
WHERE ordered_at >= CURRENT_DATE - INTERVAL '1 day'
  AND ordered_at < CURRENT_DATE
`

func (q *Queries) GetYesterdayOrderCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getYesterdayOrderCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getYesterdayRevenue = `-- name: GetYesterdayRevenue :one
SELECT COALESCE(SUM(m.price * o.quantity), 0)::FLOAT as revenue
FROM orders o
JOIN menu_items m ON o.menu_item_id = m.id
WHERE o.ordered_at >= CURRENT_DATE - INTERVAL '1 day' 
  AND o.ordered_at < CURRENT_DATE
`

func (q *Queries) GetYesterdayRevenue(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, getYesterdayRevenue)
	var revenue float64
	err := row.Scan(&revenue)
	return revenue, err
}
