// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOTP = `-- name: ConsumeOTP :one
UPDATE otp_codes
SET consumed_at = now()
WHERE id = $1
RETURNING id, user_id, code_hash, expires_at, created_at, consumed_at
`

func (q *Queries) ConsumeOTP(ctx context.Context, id int64) (OtpCode, error) {
	row := q.db.QueryRow(ctx, consumeOTP, id)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ConsumedAt,
	)
	return i, err
}

const createOTP = `-- name: CreateOTP :one
INSERT INTO otp_codes (user_id, code_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, code_hash, expires_at, created_at, consumed_at
`

type CreateOTPParams struct {
	UserID    int64              `json:"user_id"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, createOTP, arg.UserID, arg.CodeHash, arg.ExpiresAt)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ConsumedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, created_at, expires_at, last_seen_at, revoked_at
`

type CreateSessionParams struct {
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, created_at, expires_at, last_seen_at, revoked_at FROM sessions
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const getValidOTP = `-- name: GetValidOTP :one
SELECT id, user_id, code_hash, expires_at, created_at, consumed_at FROM otp_codes
WHERE user_id = $1
  AND code_hash = $2
  AND consumed_at IS NULL
  AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

type GetValidOTPParams struct {
	UserID   int64  `json:"user_id"`
	CodeHash string `json:"code_hash"`
}

func (q *Queries) GetValidOTP(ctx context.Context, arg GetValidOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getValidOTP, arg.UserID, arg.CodeHash)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ConsumedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :one
UPDATE sessions
SET revoked_at = now()
WHERE id = $1
RETURNING id, user_id, token_hash, created_at, expires_at, last_seen_at, revoked_at
`

func (q *Queries) RevokeSession(ctx context.Context, id int64) (Session, error) {
	row := q.db.QueryRow(ctx, revokeSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateSessionLastSeen = `-- name: UpdateSessionLastSeen :one
UPDATE sessions
SET last_seen_at = now()
WHERE id = $1
RETURNING id, user_id, token_hash, created_at, expires_at, last_seen_at, revoked_at
`

func (q *Queries) UpdateSessionLastSeen(ctx context.Context, id int64) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionLastSeen, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}
