// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: bills.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBill = `-- name: CreateBill :one
INSERT INTO bills (vendor_id, txn_id, amount, due_date, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, vendor_id, txn_id, amount, due_date, status, created_at, updated_at
`

type CreateBillParams struct {
	VendorID int64       `json:"vendor_id"`
	TxnID    string      `json:"txn_id"`
	Amount   float64     `json:"amount"`
	DueDate  pgtype.Date `json:"due_date"`
	Status   BillStatus  `json:"status"`
}

func (q *Queries) CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error) {
	row := q.db.QueryRow(ctx, createBill,
		arg.VendorID,
		arg.TxnID,
		arg.Amount,
		arg.DueDate,
		arg.Status,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.TxnID,
		&i.Amount,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBill = `-- name: DeleteBill :exec
DELETE FROM bills
WHERE id = $1
`

func (q *Queries) DeleteBill(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteBill, id)
	return err
}

const getBill = `-- name: GetBill :one
SELECT id, vendor_id, txn_id, amount, due_date, status, created_at, updated_at FROM bills
WHERE id = $1
`

func (q *Queries) GetBill(ctx context.Context, id int64) (Bill, error) {
	row := q.db.QueryRow(ctx, getBill, id)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.TxnID,
		&i.Amount,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBills = `-- name: ListBills :many
SELECT id, vendor_id, txn_id, amount, due_date, status, created_at, updated_at FROM bills
ORDER BY id
`

func (q *Queries) ListBills(ctx context.Context) ([]Bill, error) {
	rows, err := q.db.Query(ctx, listBills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bill
	for rows.Next() {
		var i Bill
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.TxnID,
			&i.Amount,
			&i.DueDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBill = `-- name: UpdateBill :one
UPDATE bills
SET vendor_id = $2,
    txn_id = $3,
    amount = $4,
    due_date = $5,
    status = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, vendor_id, txn_id, amount, due_date, status, created_at, updated_at
`

type UpdateBillParams struct {
	ID       int64       `json:"id"`
	VendorID int64       `json:"vendor_id"`
	TxnID    string      `json:"txn_id"`
	Amount   float64     `json:"amount"`
	DueDate  pgtype.Date `json:"due_date"`
	Status   BillStatus  `json:"status"`
}

func (q *Queries) UpdateBill(ctx context.Context, arg UpdateBillParams) (Bill, error) {
	row := q.db.QueryRow(ctx, updateBill,
		arg.ID,
		arg.VendorID,
		arg.TxnID,
		arg.Amount,
		arg.DueDate,
		arg.Status,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.TxnID,
		&i.Amount,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
