// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: dining_tables.sql

package db

import (
	"context"
)

const createDiningTable = `-- name: CreateDiningTable :one
INSERT INTO dining_tables (number)
VALUES ($1)
RETURNING id, number, status, created_at, updated_at
`

func (q *Queries) CreateDiningTable(ctx context.Context, number int32) (DiningTable, error) {
	row := q.db.QueryRow(ctx, createDiningTable, number)
	var i DiningTable
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDiningTable = `-- name: DeleteDiningTable :exec
DELETE FROM dining_tables
WHERE id = $1
`

func (q *Queries) DeleteDiningTable(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDiningTable, id)
	return err
}

const getDiningTable = `-- name: GetDiningTable :one
SELECT id, number, status, created_at, updated_at FROM dining_tables
WHERE id = $1
`

func (q *Queries) GetDiningTable(ctx context.Context, id int64) (DiningTable, error) {
	row := q.db.QueryRow(ctx, getDiningTable, id)
	var i DiningTable
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDiningTables = `-- name: ListDiningTables :many
SELECT id, number, status, created_at, updated_at FROM dining_tables
ORDER BY number
`

func (q *Queries) ListDiningTables(ctx context.Context) ([]DiningTable, error) {
	rows, err := q.db.Query(ctx, listDiningTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiningTable
	for rows.Next() {
		var i DiningTable
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
