// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: ingredients.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO ingredients (menu_item_id, inventory_item_id, quantity)
VALUES ($1, $2, $3)
RETURNING id, menu_item_id, inventory_item_id, quantity, created_at, updated_at
`

type CreateIngredientParams struct {
	MenuItemID      int64   `json:"menu_item_id"`
	InventoryItemID int64   `json:"inventory_item_id"`
	Quantity        float64 `json:"quantity"`
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, createIngredient, arg.MenuItemID, arg.InventoryItemID, arg.Quantity)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.MenuItemID,
		&i.InventoryItemID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIngredient = `-- name: DeleteIngredient :exec
DELETE FROM ingredients
WHERE id = $1
`

func (q *Queries) DeleteIngredient(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteIngredient, id)
	return err
}

const deleteIngredientsByMenuItem = `-- name: DeleteIngredientsByMenuItem :exec
DELETE FROM ingredients
WHERE menu_item_id = $1
`

func (q *Queries) DeleteIngredientsByMenuItem(ctx context.Context, menuItemID int64) error {
	_, err := q.db.Exec(ctx, deleteIngredientsByMenuItem, menuItemID)
	return err
}

const getIngredient = `-- name: GetIngredient :one
SELECT id, menu_item_id, inventory_item_id, quantity, created_at, updated_at FROM ingredients
WHERE id = $1
`

func (q *Queries) GetIngredient(ctx context.Context, id int64) (Ingredient, error) {
	row := q.db.QueryRow(ctx, getIngredient, id)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.MenuItemID,
		&i.InventoryItemID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIngredients = `-- name: ListIngredients :many
SELECT id, menu_item_id, inventory_item_id, quantity, created_at, updated_at FROM ingredients
ORDER BY id
`

func (q *Queries) ListIngredients(ctx context.Context) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, listIngredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.MenuItemID,
			&i.InventoryItemID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngredientsByMenuItem = `-- name: ListIngredientsByMenuItem :many
SELECT i.id, i.menu_item_id, i.inventory_item_id, i.quantity, i.created_at, i.updated_at, inv.name as inventory_item_name, inv.unit as inventory_item_unit
FROM ingredients i
JOIN inventory_items inv ON i.inventory_item_id = inv.id
WHERE i.menu_item_id = $1
`

type ListIngredientsByMenuItemRow struct {
	ID                int64              `json:"id"`
	MenuItemID        int64              `json:"menu_item_id"`
	InventoryItemID   int64              `json:"inventory_item_id"`
	Quantity          float64            `json:"quantity"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	InventoryItemName string             `json:"inventory_item_name"`
	InventoryItemUnit string             `json:"inventory_item_unit"`
}

func (q *Queries) ListIngredientsByMenuItem(ctx context.Context, menuItemID int64) ([]ListIngredientsByMenuItemRow, error) {
	rows, err := q.db.Query(ctx, listIngredientsByMenuItem, menuItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIngredientsByMenuItemRow
	for rows.Next() {
		var i ListIngredientsByMenuItemRow
		if err := rows.Scan(
			&i.ID,
			&i.MenuItemID,
			&i.InventoryItemID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InventoryItemName,
			&i.InventoryItemUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIngredient = `-- name: UpdateIngredient :one
UPDATE ingredients
SET menu_item_id = $2,
    inventory_item_id = $3,
    quantity = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, menu_item_id, inventory_item_id, quantity, created_at, updated_at
`

type UpdateIngredientParams struct {
	ID              int64   `json:"id"`
	MenuItemID      int64   `json:"menu_item_id"`
	InventoryItemID int64   `json:"inventory_item_id"`
	Quantity        float64 `json:"quantity"`
}

func (q *Queries) UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, updateIngredient,
		arg.ID,
		arg.MenuItemID,
		arg.InventoryItemID,
		arg.Quantity,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.MenuItemID,
		&i.InventoryItemID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
