// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: inventory_items.sql

package db

import (
	"context"
)

const createInventoryItem = `-- name: CreateInventoryItem :one
INSERT INTO inventory_items (name, quantity, unit, vendor_id, category, min_stock)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, quantity, unit, vendor_id, category, min_stock, created_at, updated_at
`

type CreateInventoryItemParams struct {
	Name     string  `json:"name"`
	Quantity float64 `json:"quantity"`
	Unit     string  `json:"unit"`
	VendorID int64   `json:"vendor_id"`
	Category string  `json:"category"`
	MinStock float64 `json:"min_stock"`
}

func (q *Queries) CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, createInventoryItem,
		arg.Name,
		arg.Quantity,
		arg.Unit,
		arg.VendorID,
		arg.Category,
		arg.MinStock,
	)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Quantity,
		&i.Unit,
		&i.VendorID,
		&i.Category,
		&i.MinStock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInventoryItem = `-- name: DeleteInventoryItem :exec
DELETE FROM inventory_items
WHERE id = $1
`

func (q *Queries) DeleteInventoryItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteInventoryItem, id)
	return err
}

const getInventoryItem = `-- name: GetInventoryItem :one
SELECT id, name, quantity, unit, vendor_id, category, min_stock, created_at, updated_at FROM inventory_items
WHERE id = $1
`

func (q *Queries) GetInventoryItem(ctx context.Context, id int64) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, getInventoryItem, id)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Quantity,
		&i.Unit,
		&i.VendorID,
		&i.Category,
		&i.MinStock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInventoryItems = `-- name: ListInventoryItems :many
SELECT id, name, quantity, unit, vendor_id, category, min_stock, created_at, updated_at FROM inventory_items
ORDER BY id
`

func (q *Queries) ListInventoryItems(ctx context.Context) ([]InventoryItem, error) {
	rows, err := q.db.Query(ctx, listInventoryItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryItem
	for rows.Next() {
		var i InventoryItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Quantity,
			&i.Unit,
			&i.VendorID,
			&i.Category,
			&i.MinStock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInventoryItem = `-- name: UpdateInventoryItem :one
UPDATE inventory_items
SET name = $2,
    quantity = $3,
    unit = $4,
    vendor_id = $5,
    category = $6,
    min_stock = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, name, quantity, unit, vendor_id, category, min_stock, created_at, updated_at
`

type UpdateInventoryItemParams struct {
	ID       int64   `json:"id"`
	Name     string  `json:"name"`
	Quantity float64 `json:"quantity"`
	Unit     string  `json:"unit"`
	VendorID int64   `json:"vendor_id"`
	Category string  `json:"category"`
	MinStock float64 `json:"min_stock"`
}

func (q *Queries) UpdateInventoryItem(ctx context.Context, arg UpdateInventoryItemParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, updateInventoryItem,
		arg.ID,
		arg.Name,
		arg.Quantity,
		arg.Unit,
		arg.VendorID,
		arg.Category,
		arg.MinStock,
	)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Quantity,
		&i.Unit,
		&i.VendorID,
		&i.Category,
		&i.MinStock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
