// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AlertSeverity string

const (
	AlertSeverityInfo     AlertSeverity = "info"
	AlertSeverityWarning  AlertSeverity = "warning"
	AlertSeverityCritical AlertSeverity = "critical"
)

func (e *AlertSeverity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertSeverity(s)
	case string:
		*e = AlertSeverity(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertSeverity: %T", src)
	}
	return nil
}

type NullAlertSeverity struct {
	AlertSeverity AlertSeverity `json:"alert_severity"`
	Valid         bool          `json:"valid"` // Valid is true if AlertSeverity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertSeverity) Scan(value interface{}) error {
	if value == nil {
		ns.AlertSeverity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertSeverity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertSeverity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertSeverity), nil
}

type BillStatus string

const (
	BillStatusPending BillStatus = "pending"
	BillStatusPaid    BillStatus = "paid"
	BillStatusOverdue BillStatus = "overdue"
)

func (e *BillStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillStatus(s)
	case string:
		*e = BillStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BillStatus: %T", src)
	}
	return nil
}

type NullBillStatus struct {
	BillStatus BillStatus `json:"bill_status"`
	Valid      bool       `json:"valid"` // Valid is true if BillStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BillStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillStatus), nil
}

type OrderStatus string

const (
	OrderStatusNew       OrderStatus = "new"
	OrderStatusPreparing OrderStatus = "preparing"
	OrderStatusReady     OrderStatus = "ready"
	OrderStatusServed    OrderStatus = "served"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type TableStatus string

const (
	TableStatusAvailable TableStatus = "available"
	TableStatusOrdered   TableStatus = "ordered"
	TableStatusPreparing TableStatus = "preparing"
	TableStatusEating    TableStatus = "eating"
	TableStatusReady     TableStatus = "ready"
	TableStatusBilled    TableStatus = "billed"
)

func (e *TableStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TableStatus(s)
	case string:
		*e = TableStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TableStatus: %T", src)
	}
	return nil
}

type NullTableStatus struct {
	TableStatus TableStatus `json:"table_status"`
	Valid       bool        `json:"valid"` // Valid is true if TableStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTableStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TableStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TableStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTableStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TableStatus), nil
}

type UserRole string

const (
	UserRoleWaiter  UserRole = "waiter"
	UserRoleManager UserRole = "manager"
	UserRoleAdmin   UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Alert struct {
	ID          int64              `json:"id"`
	Type        string             `json:"type"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Severity    AlertSeverity      `json:"severity"`
	IsRead      bool               `json:"is_read"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Bill struct {
	ID        int64              `json:"id"`
	VendorID  int64              `json:"vendor_id"`
	TxnID     string             `json:"txn_id"`
	Amount    float64            `json:"amount"`
	DueDate   pgtype.Date        `json:"due_date"`
	Status    BillStatus         `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type DiningTable struct {
	ID        int64              `json:"id"`
	Number    int32              `json:"number"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Ingredient struct {
	ID              int64              `json:"id"`
	MenuItemID      int64              `json:"menu_item_id"`
	InventoryItemID int64              `json:"inventory_item_id"`
	Quantity        float64            `json:"quantity"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type InventoryItem struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Quantity  float64            `json:"quantity"`
	Unit      string             `json:"unit"`
	VendorID  int64              `json:"vendor_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Category  string             `json:"category"`
	MinStock  pgtype.Float8      `json:"min_stock"`
}

type MenuItem struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Price       float64            `json:"price"`
	IsAvailable bool               `json:"is_available"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Category    string             `json:"category"`
	Description pgtype.Text        `json:"description"`
}

type Order struct {
	ID         int64              `json:"id"`
	MenuItemID int64              `json:"menu_item_id"`
	Quantity   int32              `json:"quantity"`
	TableID    int64              `json:"table_id"`
	OrderedAt  pgtype.Timestamptz `json:"ordered_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Status     OrderStatus        `json:"status"`
}

type OtpCode struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	CodeHash   string             `json:"code_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
}

type Session struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type User struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Role      UserRole           `json:"role"`
	Phone     string             `json:"phone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Vendor struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Address   string             `json:"address"`
	Email     string             `json:"email"`
	Phone     string             `json:"phone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
