// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (menu_item_id, quantity, table_id, ordered_at, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, menu_item_id, quantity, table_id, ordered_at, status, created_at, updated_at
`

type CreateOrderParams struct {
	MenuItemID int64              `json:"menu_item_id"`
	Quantity   int32              `json:"quantity"`
	TableID    int64              `json:"table_id"`
	OrderedAt  pgtype.Timestamptz `json:"ordered_at"`
	Status     OrderStatus        `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.MenuItemID,
		arg.Quantity,
		arg.TableID,
		arg.OrderedAt,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.MenuItemID,
		&i.Quantity,
		&i.TableID,
		&i.OrderedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders
WHERE id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteOrder, id)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT id, menu_item_id, quantity, table_id, ordered_at, status, created_at, updated_at FROM orders
WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.MenuItemID,
		&i.Quantity,
		&i.TableID,
		&i.OrderedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, menu_item_id, quantity, table_id, ordered_at, status, created_at, updated_at FROM orders
ORDER BY id
`

func (q *Queries) ListOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.MenuItemID,
			&i.Quantity,
			&i.TableID,
			&i.OrderedAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE orders
SET menu_item_id = $2,
    quantity = $3,
    table_id = $4,
    ordered_at = $5,
    status = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, menu_item_id, quantity, table_id, ordered_at, status, created_at, updated_at
`

type UpdateOrderParams struct {
	ID         int64              `json:"id"`
	MenuItemID int64              `json:"menu_item_id"`
	Quantity   int32              `json:"quantity"`
	TableID    int64              `json:"table_id"`
	OrderedAt  pgtype.Timestamptz `json:"ordered_at"`
	Status     OrderStatus        `json:"status"`
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrder,
		arg.ID,
		arg.MenuItemID,
		arg.Quantity,
		arg.TableID,
		arg.OrderedAt,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.MenuItemID,
		&i.Quantity,
		&i.TableID,
		&i.OrderedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
