// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: vendors.sql

package db

import (
	"context"
)

const createVendor = `-- name: CreateVendor :one
INSERT INTO vendors (name, address, email, phone, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, address, email, phone, status, created_at, updated_at
`

type CreateVendorParams struct {
	Name    string `json:"name"`
	Address string `json:"address"`
	Email   string `json:"email"`
	Phone   string `json:"phone"`
	Status  string `json:"status"`
}

func (q *Queries) CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, createVendor,
		arg.Name,
		arg.Address,
		arg.Email,
		arg.Phone,
		arg.Status,
	)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVendor = `-- name: DeleteVendor :exec
DELETE FROM vendors
WHERE id = $1
`

func (q *Queries) DeleteVendor(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteVendor, id)
	return err
}

const getVendor = `-- name: GetVendor :one
SELECT id, name, address, email, phone, status, created_at, updated_at FROM vendors
WHERE id = $1
`

func (q *Queries) GetVendor(ctx context.Context, id int64) (Vendor, error) {
	row := q.db.QueryRow(ctx, getVendor, id)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVendors = `-- name: ListVendors :many
SELECT id, name, address, email, phone, status, created_at, updated_at FROM vendors
ORDER BY id
`

func (q *Queries) ListVendors(ctx context.Context) ([]Vendor, error) {
	rows, err := q.db.Query(ctx, listVendors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vendor
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Email,
			&i.Phone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVendor = `-- name: UpdateVendor :one
UPDATE vendors
SET name = $2,
    address = $3,
    email = $4,
    phone = $5,
    status = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, name, address, email, phone, status, created_at, updated_at
`

type UpdateVendorParams struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Address string `json:"address"`
	Email   string `json:"email"`
	Phone   string `json:"phone"`
	Status  string `json:"status"`
}

func (q *Queries) UpdateVendor(ctx context.Context, arg UpdateVendorParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, updateVendor,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Email,
		arg.Phone,
		arg.Status,
	)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
